# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/Volodymyr
Accept: application/json

###

GET http://127.0.0.1:8000/calculate?operation=%2B&a=31&b=50
Accept: application/json

###

GET http://127.0.0.1:8000/calculate?operation=%-&a=31&b=50
Accept: application/json